font:
  normal:
    family: Fira Mono
    style: Regular
  bold:
    family: Fira Mono
    style: Bold
  italic:
    family: Fira Mono
    style: Italic
  bold_italic:
    family: Fira Mono
    style: Italic
  size: 12.0
  offset:
    y: 3

colors:
  primary:
    background: '0x242323'
    foreground: '0xa5979a'

  cursor:
    text: '0x242323'
    cursor: '0xe24f32'

  normal:
    black:   '0x242323'
    red:     '0x956f76'
    green:   '0xffa28f'
    yellow:  '0xffc8bd'
    blue:    '0xa7868b'
    magenta: '0xf77c64'
    cyan:    '0xb89da2'
    white:   '0xa5979a'

draw_bold_text_with_bright_colors: false

# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
background_opacity: 0.95
