font:
  normal:
    family: IBM Plex Mono
    style: Regular
  bold:
    family: IBM Plex Mono
    style: Bold
  italic:
    family: IBM Plex Mono
    style: Italic
  bold_italic:
    family: IBM Plex Mono
    style: Italic
  size: 11.0
  offset:
    y: 3

# Colors (Oceanic Next)
colors:
  # Default colors
  primary:
    background: '0x1b2b34'
    foreground: '0xd8dee9'

  # Normal colors
  normal:
    black:   '0x29414f'
    red:     '0xec5f67'
    green:   '0x99c794'
    yellow:  '0xfac863'
    blue:    '0x6699cc'
    magenta: '0xc594c5'
    cyan:    '0x5fb3b3'
    white:   '0x65737e'

  # Bright colors
  bright:
    black:   '0x405860'
    red:     '0xec5f67'
    green:   '0x99c794'
    yellow:  '0xfac863'
    blue:    '0x6699cc'
    magenta: '0xc594c5'
    cyan:    '0x5fb3b3'
    white:   '0xadb5c0'
# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
background_opacity: 0.95

shell:
  program: /usr/bin/fish
  args:
    - --login
