font:
  normal:
    family: Fira Mono
    style: Regular
  bold:
    family: Fira Mono
    style: Bold
  italic:
    family: Fira Mono
    style: Italic
  bold_italic:
    family: Fira Mono
    style: Italic
  size: 12.0
  offset:
    y: 3

colors:
  primary:
    background: '0x212121'
    foreground: '0xf1f1f1'

  cursor:
    text: '0xf1f1f1'
    cursor: '0x20bbfc'

  normal:
    black:   '0x212121'
    red:     '0xc30771'
    green:   '0x10a778'
    yellow:  '0xa89c14'
    blue:    '0x008ec4'
    magenta: '0x523c79'
    cyan:    '0x20a5ba'
    white:   '0xf1f1f1'
  bright:
    black:   '0x424242'
    red:     '0xfb007a'
    green:   '0x5fd7af'
    yellow:  '0xf3e430'
    blue:    '0x20bbfc'
    magenta: '0x6855de'
    cyan:    '0x4fb8cc'
    white:   '0xd9d9d9'


draw_bold_text_with_bright_colors: false

# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
background_opacity: 0.95
