font:
  normal:
    family: iA Writer Mono S
    style: Regular
  bold:
    family: iA Writer Mono S
    style: Bold
  italic:
    family: iA Writer Mono S
    style: Italic
  bold_italic:
    family: iA Writer Mono S
    style: Italic
  size: 12.0
  offset:
    y: 2

# Base16 Grayscale Light - alacritty color config
# Alexandre Gavioli (https://github.com/Alexx2/)
colors:
  # Default colors
  primary:
    background: '0xf7f7f7'
    foreground: '0x464646'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf7f7f7'
    cursor: '0x464646'

  # Normal colors
  normal:
    black:   '0xf7f7f7'
    red:     '0x7c7c7c'
    green:   '0x8e8e8e'
    yellow:  '0xa0a0a0'
    blue:    '0x686868'
    magenta: '0x747474'
    cyan:    '0x868686'
    white:   '0x464646'

  # Bright colors
  bright:
    black:   '0xababab'
    red:     '0x999999'
    green:   '0xe3e3e3'
    yellow:  '0xb9b9b9'
    blue:    '0x525252'
    magenta: '0x252525'
    cyan:    '0x5e5e5e'
    white:   '0x101010'

draw_bold_text_with_bright_colors: false

# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
background_opacity: 0.95

